//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Area_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Area_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Bar_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Bar_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Donut_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Donut_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Gantt_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Gantt_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Gauge_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Gauge_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Grid_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Grid_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Heat_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Heat_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Line_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Line_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Pie_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Pie_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Scatter_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Scatter_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_StepLine_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_StepLine_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Chart_Table_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Chart_Table_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Data_DataSet_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Data_DataSet_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Browser_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Browser_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Button_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Button_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Calendar_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Calendar_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_CheckBox_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_CheckBox_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Checklist_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Checklist_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Clock_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Clock_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_ColorCanvas_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_ColorCanvas_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_ColorCanvasDrop_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_ColorCanvasDrop_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_ColorEyeDropper2_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_ColorEyeDropper2_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_ColorPicker_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_ColorPicker_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_ColorPickerDrop_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_ColorPickerDrop_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_ColorSlider_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_ColorSlider_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_CommandGet_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_CommandGet_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_CommandLoad_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_CommandLoad_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_CommandRun_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_CommandRun_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_CommandSave_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_CommandSave_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_DateTime_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_DateTime_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Dropdown_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Dropdown_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Gradients_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Gradients_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Image_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Image_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Integer_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Integer_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Label_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Label_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Legend_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Legend_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_ListBox_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_ListBox_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_PickDate_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_PickDate_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_PickTime_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_PickTime_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Radio_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Radio_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_RangeSlider_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_RangeSlider_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_RhinoViewer_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_RhinoViewer_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_ScrollNumber_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_ScrollNumber_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_ScrollText_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_ScrollText_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Slider_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Slider_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Spacer_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Spacer_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_TextBlock_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_TextBlock_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_TextBox_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_TextBox_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Elements_Toggle_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Elements_Toggle_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Export_Image_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Export_Image_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Export_Print_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Export_Print_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Border_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Border_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Card_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Card_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Dock_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Dock_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Expander_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Expander_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Grid_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Grid_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Placement_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Placement_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Scroller_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Scroller_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Stack_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Stack_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Tabs_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Tabs_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Layouts_Wrap_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Layouts_Wrap_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Logo_16alt {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Logo_16alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Logo_24 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Logo_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_Align_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_Align_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_DataCell_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_DataCell_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_DataGraphics_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_DataGraphics_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_DataLabels_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_DataLabels_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_DataPopups_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_DataPopups_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_DataSetAxis_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_DataSetAxis_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_DataSetGraphics_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_DataSetGraphics_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_DataSetLegend_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_DataSetLegend_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_Font_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_Font_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_Graphics_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_Graphics_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_ModChart_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_ModChart_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_Offset_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_Offset_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_OffsetEven_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_OffsetEven_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Modify_Resize_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Modify_Resize_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Utility_Listen_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Utility_Listen_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Utility_Update_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Utility_Update_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UiPlus_Window_Launch_01 {
            get {
                object obj = ResourceManager.GetObject("UiPlus_Window_Launch_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
